#!/usr/bin/env bash
# Build current tree and rsync dist/ to beta.heliopoly.live (GitHub main).
# Does NOT write /var/www/heliopoly (live) or heliopoly-releases/ (Sunday stage).
#
# Usage:
#   ./scripts/deploy-beta.sh
#   ./scripts/deploy-beta.sh --dry-run
#   ./scripts/deploy-beta.sh --skip-build   # dist/ already built (CI)
set -euo pipefail

DRY_RUN=0
SKIP_BUILD=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "unknown arg: $arg (try --dry-run / --skip-build)" >&2
      exit 2
      ;;
  esac
done

# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")" && pwd)/deploy-common.sh"
cd "$REPO_ROOT"

BETA_ROOT="${HELIOPOLY_BETA_ROOT:-/var/www/heliopoly-beta}"
BETA_URL="${HELIOPOLY_BETA_URL:-https://beta.heliopoly.live/}"
PKG_VERSION="$(python3 -c 'import json; print(json.load(open("package.json"))["version"])')"
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

if [[ "$SKIP_BUILD" -ne 1 ]]; then
  echo "→ npm run build"
  npm run build
fi
if [[ ! -f dist/index.html ]]; then
  echo "ERROR: dist/index.html missing" >&2
  exit 1
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "→ dry-run rsync dist/ → ${HELIOPOLY_DEPLOY_HOST}:${BETA_ROOT}/"
  rsync -avzn --delete -e "$RSYNC_RSH" dist/ "${DEPLOY_TARGET}:${BETA_ROOT}/"
  echo "OK dry-run (beta unchanged)"
  exit 0
fi

echo "→ install nginx vhosts (beta + preview 301)"
"${SSH[@]}" "$DEPLOY_TARGET" "mkdir -p '${BETA_ROOT}' /var/www/acme /etc/nginx/snippets /etc/nginx/sites-available /etc/nginx/sites-enabled"
rsync -vz --no-owner --no-group --no-perms -e "$RSYNC_RSH" \
  "$REPO_ROOT/scripts/nginx/heliopoly-beta" \
  "${DEPLOY_TARGET}:/etc/nginx/sites-available/heliopoly-beta"
rsync -vz --no-owner --no-group --no-perms -e "$RSYNC_RSH" \
  "$REPO_ROOT/scripts/nginx/heliopoly-preview" \
  "${DEPLOY_TARGET}:/etc/nginx/sites-available/heliopoly-preview"
"${SSH[@]}" "$DEPLOY_TARGET" "ln -sfn /etc/nginx/sites-available/heliopoly-beta /etc/nginx/sites-enabled/heliopoly-beta && ln -sfn /etc/nginx/sites-available/heliopoly-preview /etc/nginx/sites-enabled/heliopoly-preview"

BETA_BANNER="# Generated by deploy-beta.sh — beta host only.
sub_filter '<body>' '<body><div id=\"hp-preview-bar\" style=\"position:fixed;top:0;left:0;right:0;z-index:4000;height:36px;background:#c9a227;color:#0b1020;font:600 13px/36px system-ui,sans-serif;text-align:center;\">Beta · ${PKG_VERSION} · ${GIT_SHA} · GitHub main · not heliopoly.live</div>';
sub_filter_once on;
"
echo "$BETA_BANNER" | "${SSH[@]}" "$DEPLOY_TARGET" "cat > /etc/nginx/snippets/heliopoly-beta-banner.conf"

echo "→ expand TLS SAN for beta.heliopoly.live if missing"
"${SSH[@]}" "$DEPLOY_TARGET" "nginx -t && systemctl reload nginx"
"${SSH[@]}" "$DEPLOY_TARGET" "python3 - <<'PY'
import subprocess, sys
out = subprocess.check_output(
    ['openssl', 'x509', '-in', '/etc/letsencrypt/live/heliopoly.live/fullchain.pem', '-noout', '-text'],
    text=True,
)
if 'DNS:beta.heliopoly.live' in out:
    print('cert already has beta.heliopoly.live')
    sys.exit(0)
print('→ certbot --expand add beta.heliopoly.live')
r = subprocess.run([
    'certbot', 'certonly', '--cert-name', 'heliopoly.live',
    '--webroot', '-w', '/var/www/acme', '--expand', '--non-interactive',
    '--agree-tos',
    '-d', 'heliopoly.live',
    '-d', 'www.heliopoly.live',
    '-d', 'preview.heliopoly.live',
    '-d', 'sim.heliopoly.live',
    '-d', 'simulation.heliopoly.live',
    '-d', 'beta.heliopoly.live',
], check=False)
sys.exit(r.returncode)
PY"

echo "→ rsync dist/ → ${HELIOPOLY_DEPLOY_HOST}:${BETA_ROOT}/"
rsync -avz --delete -e "$RSYNC_RSH" dist/ "${DEPLOY_TARGET}:${BETA_ROOT}/"

"${SSH[@]}" "$DEPLOY_TARGET" "nginx -t && systemctl reload nginx"

echo "→ verify ${BETA_URL}"
html="$(curl -fsS -H 'Cache-Control: no-cache' -L "$BETA_URL")"
if ! grep -q 'title-tagline' <<<"$html"; then
  echo "ERROR: beta index missing title-tagline" >&2
  exit 1
fi
echo "OK beta ${PKG_VERSION} ${GIT_SHA} ${BETA_URL} (live unchanged)"
