#!/usr/bin/env bash
# Build current tree and stage dist/ on the .live droplet for Sunday promote.
# Does NOT write into /var/www/heliopoly (live). Only heliopoly-releases/.
#
# Usage (from Mac with deploy key):
#   ./scripts/stage-release-for-live.sh 0.0.26 2026-08-16T00:01:00.000Z
set -euo pipefail

VERSION="${1:?version e.g. 0.0.26}"
ENABLED_AFTER="${2:?ISO unlock e.g. 2026-08-16T00:01:00.000Z}"
# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")" && pwd)/deploy-common.sh"
REMOTE_RELEASES=/var/www/heliopoly-releases
REMOTE_VER="${REMOTE_RELEASES}/${VERSION}"

cd "$REPO_ROOT"
npm run build

echo "→ stage dist/ → ${HELIOPOLY_DEPLOY_HOST}:${REMOTE_VER}/"
"${SSH[@]}" "$DEPLOY_TARGET" "mkdir -p '${REMOTE_VER}' '${REMOTE_RELEASES}'"
rsync -avz --delete -e "$RSYNC_RSH" dist/ "${DEPLOY_TARGET}:${REMOTE_VER}/"

PENDING_JSON=$(cat <<EOF
{
  "version": "${VERSION}",
  "enabledAfter": "${ENABLED_AFTER}",
  "comment": "Weekly promote to heliopoly.live (UTC)",
  "stagedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "gitDescribe": "$(git describe --tags --always 2>/dev/null || echo unknown)"
}
EOF
)

echo "→ write pending.json (unlock ${ENABLED_AFTER})"
echo "$PENDING_JSON" | "${SSH[@]}" "$DEPLOY_TARGET" "cat > '${REMOTE_RELEASES}/pending.json'"

echo "→ point preview.heliopoly.live at staged ${VERSION} (does not touch live web root)"
"${SSH[@]}" "$DEPLOY_TARGET" "ln -sfn '${REMOTE_VER}' /var/www/heliopoly-preview-current"
PREVIEW_BANNER="# Generated by stage-release-for-live.sh — preview host only.
sub_filter_types text/html;
sub_filter '<body>' '<body><div id=\"hp-preview-bar\" style=\"position:fixed;top:0;left:0;right:0;z-index:4000;height:36px;background:#c9a227;color:#0b1020;font:600 13px/36px system-ui,sans-serif;text-align:center;\">Preview · ${VERSION} · unlocks Sunday 00:01 UTC · not heliopoly.live</div>';
sub_filter_once on;
"
echo "$PREVIEW_BANNER" | "${SSH[@]}" "$DEPLOY_TARGET" "cat > /etc/nginx/snippets/heliopoly-preview-banner.conf"
"${SSH[@]}" "$DEPLOY_TARGET" "nginx -t && systemctl reload nginx"


echo "→ install promote script + weekly cron (idempotent)"
# Do not rsync -a into /etc/cron.d — archive mode preserves the Mac uid
# (501:staff). Debian cron then rejects the file: WRONG FILE OWNER.
rsync -vz --no-owner --no-group --no-perms -e "$RSYNC_RSH" \
  scripts/heliopoly-promote-next.sh \
  "${DEPLOY_TARGET}:/usr/local/bin/heliopoly-promote-next"
"${SSH[@]}" "$DEPLOY_TARGET" "chown root:root /usr/local/bin/heliopoly-promote-next && chmod 755 /usr/local/bin/heliopoly-promote-next"
rsync -vz --no-owner --no-group --no-perms -e "$RSYNC_RSH" \
  scripts/heliopoly-promote.cron \
  "${DEPLOY_TARGET}:/etc/cron.d/heliopoly-promote"
"${SSH[@]}" "$DEPLOY_TARGET" "chown root:root /etc/cron.d/heliopoly-promote && chmod 644 /etc/cron.d/heliopoly-promote"

echo "→ verify stage (live web root unchanged)"
"${SSH[@]}" "$DEPLOY_TARGET" "python3 - <<'PY'
import json
p=json.load(open('/var/www/heliopoly-releases/pending.json'))
print('pending', p)
import os
print('staged index', os.path.exists(f\"/var/www/heliopoly-releases/{p['version']}/index.html\"))
print('cron', open('/etc/cron.d/heliopoly-promote').read())
PY
grep -oE '[0-9]+\\.[0-9]+\\.[0-9]+' /var/www/heliopoly/index.html | head -1
"

echo "OK: ${VERSION} staged; live promotes at ${ENABLED_AFTER} via droplet cron (Sunday 00:01 UTC)."
